config/routes.rb
WhereIsMyBusServer::Application.routes.draw do

  get "city/index"

  get "city/show"

  get "transports/show"

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    post "create_broadcast" => "v1::api#create_broadcast"
    put "update_broadcast" => "v1::api#update_broadcast"

    get "status" => "v1::api#status"
    

    post "update_user" => "v1::api#update_user"
    post "create_watchdog_checkpoint" => "v1::api#create_watchdog_checkpoint"
    put "update_watchdog_checkpoint" => "v1::api#update_watchdog_checkpoint"
    delete "destroy_watchdog_checkpoint" => "v1::api#destroy_watchdog_checkpoint"

    get "get_basic_info_about_user" => "v1::api#get_basic_info_about_specefic_user"
    get "get_basic_info_about_specefic_watchdog" => "v1::api#get_basic_info_about_specefic_watchdog"
    get "get_basic_info_about_specefic_broadcats" => "v1::api#get_basic_info_about_specefic_broadcast"
    get "get_basic_info_about_specefic_city" => "v1::api#get_basic_info_about_specefic_city"

    get "say_warning" => "v1::api#say_warning"
    get "say_thanks" => "v1::api#say_thanks"

    get "get_watchdog_list" => "v1::api#get_watchdog_list"
    get "broadcasts" => "v1::api#broadcasts"
  end
  
  root to: "home_page#index"

  get "/review", to: "reviews#new", as: "review"
  post "/post", to: "reviews#create", as: "post_review"
  get "/search", to: "home_page#search"
  
  
  match "howitworks", to: "home_page#tour", as: "howitworks"
  match "terms", to: "home_page#terms", as: "terms"
  match "support", to: "home_page#support", as: "support"

  get "cities", to: "city#index", as: "cities"
  get "cities/:url_type", to: "city#show", as: "city"

  get '/top', to: "users#top", as: "user_top"
  get '/:phone_number', to: "users#show", as: :user
  get '/:phone_number/transports', to: "users#transports", as: "user_transports"
  

end

app/models/user.rb
class User
  include Mongoid::Document

  ## Database authenticatable

  field :username,        :type => String, :default => ""
  field :device_id,       :type => String, :default => ""
  index( {device_id: 1, username: 1 },{ unique: true })

  field :phone_number,   :type => String, :default => "" 
  index({phone_number: 1}, {unique: true} )

  field :language,           :type => String, :default => ""
  field :email,              :type => String, :default => ""
  field :city,               :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  field :rank, type: Integer, :default => 0
  index({rank: -1}, {unique: false} )
  
  field :position_in_top_world, type: Integer
  field :position_in_top_local, type: Integer
  before_create { self.position_in_top_local = User.all.size and self.position_in_top_world = User.all.size}

  field :thanks_count, type: Integer, default: 0
  field :say_thanks_count, type: Integer, default: 0
  field :warnings_count, type: Integer, default: 0


  field :take_part_in_the_top, type: Boolean, default: true

  has_many :transports
  has_many :broadcast, dependent: :destroy
  #has_many :activities, dependent: :destroy

  embeds_many :activities
  def to_param
    phone_number.to_s
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		
	end
	def show
		@user = User.find_by(phone_number: params[:phone_number].downcase)
		@user_count_local = User.where(city: @user.city).size
		@user_count_world = User.all.size
	end

	def transports
		@user = User.find_by(phone_number: params[:phone_number])
	end

	def top
		@world_tab_active = ""
		@local_tab_active = "active"
		if params[:location] != "world"
			@top_title = "#{ t 'user_top_in_city'} #{params[:location]}"
			@world_tab_active = ""
			@local_tab_active = "active"
			@users = User.where(city: params[:location],take_part_in_the_top: true).desc(:rank).limit(10)

		elsif params[:location] == "world"
			@top_title = "#{t 'user_top_in_world'}"
			@world_tab_active = "active"
			@local_tab_active = ""
			@users = User.where(take_part_in_the_top: true).desc(:rank).limit(10)
		else
			render nothing: true, status: 404
		end
	end

	def world_top
		@users = User.all.desc(:rank).limit(10)
	end



end

app/helpers/users_helper.rb
module UsersHelper

	def get_user_stats(user)
  # has_many :broadcasters, dependent: :destroy
  # has_many :activities, dependent: :destroy
	end

end

app/views/users/_navigation_bar.html.erb
<div class="col-12">
	<div class="btn-group btn-group-justified">
		<%= link_to "#{t 'user_navigation_header.statistic'}", user, class: "btn btn-default" %>
		<%= link_to "#{t 'user_navigation_header.transports'}", user_transports_path(user), class: "btn btn-default" %>
		<%= link_to "#{t 'user_navigation_header.settings'}", user_transports_path(user), class: "btn btn-default" %>
	</div>
</div>

app/views/users/show.html.erb
<% content_for :title, "WIMB - #{t 'statistic'} #{@user.username}" %>
<% content_for :content do %>
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="box-shadow">
					<div class="panel panel-primary" style="margin-left:0px;">
						<div class="panel-heading">
							<div style="text-align:center;"> <%= " #{t 'statistic'} #{@user.username}" %> 
							</div>
						</div>
						<div class="row">
							<table class="table table-striped" >
					  			<tbody>
					  				<tr>
					  					<td  style="text-align: right; width:50%;"> <%= t "most_popular_transport_type"%> </td> <td style="text-align: left;"> <%= t "transports.bus" %> </td>
					  				</tr>
					  				<tr>
					  					<td  style="text-align: right; width:50%;"> <%= t "most_popular_transport_number"%> </td> <td style="text-align: left;"> 21 </td>
					  				</tr>
					  				<tr>
					  					<td  style="text-align: right; width:50%;"> <%= t "broadcasts_count"%> </td> <td style="text-align: left;"> 8 </td>
					  				</tr>
					  				<tr>
					  					<td  style="text-align: right; width:50%;"> <%= t "watchdog_warnings_count"%> </td> <td style="text-align: left;"> 5 </td>
					  				</tr>
					  				<tr>
					  					<td  style="text-align: right; width:50%;">  <%= "#{t 'say_thanks.from_owner'} " %> </td> <td style="text-align: left;"> <%= "#{@user.say_thanks_count} #{t 'say_thanks.humans'}"%> </td>
					  				</tr>
					  				<tr>
					  					<td  style="text-align: right; width:50%;">  <%= "#{t 'say_thanks.from_users'} " %> </td> <td style="text-align: left;"> <%= "#{@user.thanks_count} #{t 'say_thanks.humans'}"%> </td>
					  				</tr>
					  				<tr>
					  					<td  style="text-align: right; width:50%;">  <%= "#{t 'disagre_count.body'} " %> </td> <td style="text-align: left;"> <%= "#{@user.warnings_count} #{t 'disagre_count.end'}"%> </td>
					  				</tr>
							</table>
							<div class="col-12" style="text-align:center;">
								<span class="label label-success"> <%= "#{t 'rating_position.position_local'} (#{@user.city}) #{@user.position_in_top_local} #{t 'rating_position.from'} #{@user_count_local} | #{t 'rank'} #{@user.rank}"%> </span>  
									<%= link_to "#{t 'user_top_in_city'} #{@user.city}", user_top_path(location: @user.city) ,style: "position:absolute; text-align: left; margin-left:4px;" %>
							</div>
							<div class="col-12" style="text-align:center; margin-top:10px;">
								<%= link_to "#{t 'share'}", '#', class: "btn btn-primary" %>
							</div>
						</div>

					</div>
				</div>
			</div>

		</div>
	</div>
<% end %>

app/views/users/top.html.erb
<% content_for :title, "WIMB - #{@top_title}" %>
<% content_for :content do %>
	<div class="container">
		<div class="panel" style="margin-left:0px;">

			<ul class="nav nav-tabs nav-justified">
				<li class="<%= @local_tab_active %>"><%= link_to "#{ t 'user_top_in_city'} #{@current_city}", user_top_path(location: @current_city)%></li>
				<li class="<%= @world_tab_active %>"><%= link_to "#{ t 'user_top_in_world'}", user_top_path(location: "world"), style:"text-aling:right;"%></li>
			</ul>
			<div class="container">
				<table class="table table-striped table-bordered" >
		  			<tbody>
		  				<tr>
			  				<td  style="text-align: center; width:30%;"> <%= t "position_in_top"%> </td> <td style="text-align: center;"> <%= t 'user' %> </span> </td>
			  			</tr>
		  				<% @users.each_with_index do |user, i|%>
			  				<tr>
			  					<% if params[:location] == "world"%>
								<td  style="text-align: center; width:30%;"> <%= i + 1 %> </td> <td style="text-align: center;"> <%= link_to "#{user.username}", user %>  <span class="label label-info"><%= "#{user.rank} (#{user.city})" %> </td>
								<% else %>
									<td  style="text-align: center; width:30%;"> <%= i + 1 %> </td> <td style="text-align: center;"> <%= link_to "#{user.username}", user %>  <span class="label label-info"><%= user.rank %> </td>
								<% end %> 
			  				</tr>
			  			<% end %>
		  			</tbody>
				</table>
			</div>
		</div>
	</div>
<% end %>