config/routes.rb
WhereIsMyBusServer::Application.routes.draw do

  get "city/index"

  get "city/show"

  get "transports/show"

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    post "create_broadcast" => "v1::api#create_broadcast"
    put "update_broadcast" => "v1::api#update_broadcast"

    get "status" => "v1::api#status"
    

    post "update_user" => "v1::api#update_user"
    post "create_watchdog_checkpoint" => "v1::api#create_watchdog_checkpoint"
    put "update_watchdog_checkpoint" => "v1::api#update_watchdog_checkpoint"
    delete "destroy_watchdog_checkpoint" => "v1::api#destroy_watchdog_checkpoint"

    get "get_basic_info_about_user" => "v1::api#get_basic_info_about_specefic_user"
    get "get_basic_info_about_specefic_watchdog" => "v1::api#get_basic_info_about_specefic_watchdog"
    get "get_basic_info_about_specefic_broadcats" => "v1::api#get_basic_info_about_specefic_broadcast"
    get "get_basic_info_about_specefic_city" => "v1::api#get_basic_info_about_specefic_city"

    get "say_warning" => "v1::api#say_warning"
    get "say_thanks" => "v1::api#say_thanks"

    get "get_watchdog_list" => "v1::api#get_watchdog_list"
    get "broadcasts" => "v1::api#broadcasts"
  end
  
  root to: "home_page#index"

  get "/review", to: "reviews#new", as: "review"
  post "/post", to: "reviews#create", as: "post_review"
  get "/search", to: "home_page#search"
  
  
  match "howitworks", to: "home_page#tour", as: "howitworks"
  match "terms", to: "home_page#terms", as: "terms"
  match "support", to: "home_page#support", as: "support"

  get "cities", to: "city#index", as: "cities"
  get "cities/:url_type", to: "city#show", as: "city"

  get '/top', to: "users#top", as: "user_top"
  get '/:phone_number', to: "users#show", as: :user
  get '/:phone_number/transports', to: "users#transports", as: "user_transports"
  

end

app/models/city.rb
class City
  include Mongoid::Document
  
  field :caption, type: String, default: ""
  validates :caption, uniqueness: true

  field :url_type, type: String, default: ""
  index({url_type: 1}, {unique: true} )
  validates :url_type, uniqueness: true


  field :users_count, type: Integer, default: 0
  field :transports_count, type: Integer, default: 0
  field :transports, type: Array, default: []
  field :broadcasts_count, type: Integer, default: 0
  field :warnings_count, type: Integer, default: 0

  before_save :convert_to_url_type



  def to_param
    url_type
  end

  private
  
  def convert_to_url_type
  	self.url_type = self.caption.downcase.gsub(' ','-')
  end

end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def index
  	@cities = City.all
  end

  def show
  	@city = City.find_by(url_type: params[:url_type])
  end
end

app/helpers/city_helper.rb
module CityHelper
end

app/views/city/index.html.erb
<% content_for :title, "WIMB - #{t 'cities'}" %>
<% content_for :user_front do %>
	<div class="container">
		<div class="panel" style="margin-left:0px;">

			<div class="container">
				<table class="table table-striped table-bordered" >
		  			<tbody>
		  				<tr> 
			  				<td style="text-align: center; width:30%;"> <%= t 'city' %> </td>
			  				<td style="text-align: center;"> <small> <%= t 'users_count' %> </small> </td>
			  				<td style="text-align: center;"> <small> <%= t 'added_transport_count' %> </small> </td>
			  				<td style="text-align: center;"> <small> <%= t 'broadcasts_count' %> </small> </td>
			  				<td style="text-align: center;"> <small> <%= t 'watchdog_warnings_count' %> </small> </td>
			  			</tr>

		  				<% @cities.each do |city|%>
			  				<tr>
								<td  style="text-align: center; width:50%;"> <%= link_to city.caption, city_path(city) %> </td>
								<td  style="text-align: center; width:10%;"> <%= city.users_count %> </td>
								<td  style="text-align: center; width:10%;"> <%= city.transports_count %> </td>
								<td  style="text-align: center; width:10%;"> <%= city.broadcasts_count %> </td>
								<td  style="text-align: center; width:10%;"> <%= city.warnings_count %> </td>
			  				</tr>
			  			<% end %>

		  			</tbody>
				</table>
			</div>
		</div>
	</div>
<% end %>

app/views/city/show.html.erb
<% content_for :google_chart_framework do %>
	<script type="text/javascript" src="https://www.google.com/jsapi"></script>
	<script type="text/javascript">

      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Slices');
        data.addRows([
          ["<%= t('users_count') + ' ' + @city.users_count.to_s %>", <%= @city.users_count %>],
          ["<%= t('broadcasts_count') + ' ' + @city.broadcasts_count.to_s %>", <%= @city.broadcasts_count %>],
          ["<%= t('watchdog_warnings_count') + ' ' + @city.warnings_count.to_s %>", <%= @city.warnings_count %>],
          ["<%= t('added_transport_count') + ' ' + @city.transports_count.to_s %>", <%= @city.transports_count %>]
        ]);

        // Set chart options
        var options = {pieHole: 0.4,
        				'width':600,
                       'height':600,
                       legend: {position: 'bottom'}
                   	};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
<% end %>
<% content_for :user_front do %>
	<div class="container">
		<h3 class="text-center"> <%="#{ t 'statistic_of_city' } - #{@city.caption}" %> </h3>
		<div id="chart_div"></div>
		<%= link_to "#{t 'back'}", :back %>
	</div>
<% end %>