config/routes.rb
WhereIsMyBusServer::Application.routes.draw do

  get "city/index"

  get "city/show"

  get "transports/show"

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    post "create_broadcast" => "v1::api#create_broadcast"
    put "update_broadcast" => "v1::api#update_broadcast"

    get "status" => "v1::api#status"
    

    post "update_user" => "v1::api#update_user"
    post "create_watchdog_checkpoint" => "v1::api#create_watchdog_checkpoint"
    put "update_watchdog_checkpoint" => "v1::api#update_watchdog_checkpoint"
    delete "destroy_watchdog_checkpoint" => "v1::api#destroy_watchdog_checkpoint"

    get "get_basic_info_about_user" => "v1::api#get_basic_info_about_specefic_user"
    get "get_basic_info_about_specefic_watchdog" => "v1::api#get_basic_info_about_specefic_watchdog"
    get "get_basic_info_about_specefic_broadcats" => "v1::api#get_basic_info_about_specefic_broadcast"
    get "get_basic_info_about_specefic_city" => "v1::api#get_basic_info_about_specefic_city"

    get "say_warning" => "v1::api#say_warning"
    get "say_thanks" => "v1::api#say_thanks"

    get "get_watchdog_list" => "v1::api#get_watchdog_list"
    get "broadcasts" => "v1::api#broadcasts"
  end
  
  root to: "home_page#index"

  get "/review", to: "reviews#new", as: "review"
  post "/post", to: "reviews#create", as: "post_review"
  get "/search", to: "home_page#search"
  
  
  match "howitworks", to: "home_page#tour", as: "howitworks"
  match "terms", to: "home_page#terms", as: "terms"
  match "support", to: "home_page#support", as: "support"

  get "cities", to: "city#index", as: "cities"
  get "cities/:url_type", to: "city#show", as: "city"

  get '/top', to: "users#top", as: "user_top"
  get '/:phone_number', to: "users#show", as: :user
  get '/:phone_number/transports', to: "users#transports", as: "user_transports"
  

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def new
		@categories = [{name:"categories.bug_report", id: 0}, {name:"categories.advice", id: 1}]
		render "reviews/new.html"
	end

	def create
		# if !verify_recaptcha
		UserMailer.review_mail(params).deliver
		flash[:notice] = t 'review_poster'
		respond_to do |format|
		    format.html { render 'reviews/posted.html'}
		end
	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/new.html.erb
<% content_for :title, "WIMB - #{t 'reviews'}" %>
<% content_for :content do %>
		<div class="container">
				<h1 class="span12"> <%= "#{t 'reviews'}" %>  </h1>
				<%= form_tag post_review_path do |u|%>
	
					<%= text_field_tag :title, "", placeholder: "Title", class:"span6"%> 

					<%= text_field_tag :email, "", placeholder: "Email", class:"span6"%> 

					<%= text_field_tag :subject, "", placeholder: "Subject", class:"span12"%> 

					<%= text_area_tag :body, "", class:"span12" , rows: 8 %>
					<!-- <%= recaptcha_tags %> -->
				<%= submit_tag "#{t 'send'}", class: "span4 btn btn-success"%>

				<% end %>
		</div>
<% end %>

app/views/reviews/posted.html.erb
<% content_for :title, "WIMB - #{t 'reviews'}" %>
<% content_for :content do %>
  <div class="panel" style="width:50%; text-align:center; margin:auto; vertical-align:middle; margin-top:15%; margin-bottom:15%;">
      <div class="panel-body">
    	 <h4 class="posted-notice"> <%= flash[:notice].to_s %> </h4>
      </div>
      <%= link_to "#{t 'link_to_main'}", root_path %>
  </div>

<% end %>