config/routes.rb
WhereIsMyBusServer::Application.routes.draw do

  get "city/index"

  get "city/show"

  get "transports/show"

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :api do
    post "create_broadcast" => "v1::api#create_broadcast"
    put "update_broadcast" => "v1::api#update_broadcast"

    get "status" => "v1::api#status"
    

    post "update_user" => "v1::api#update_user"
    post "create_watchdog_checkpoint" => "v1::api#create_watchdog_checkpoint"
    put "update_watchdog_checkpoint" => "v1::api#update_watchdog_checkpoint"
    delete "destroy_watchdog_checkpoint" => "v1::api#destroy_watchdog_checkpoint"

    get "get_basic_info_about_user" => "v1::api#get_basic_info_about_specefic_user"
    get "get_basic_info_about_specefic_watchdog" => "v1::api#get_basic_info_about_specefic_watchdog"
    get "get_basic_info_about_specefic_broadcats" => "v1::api#get_basic_info_about_specefic_broadcast"
    get "get_basic_info_about_specefic_city" => "v1::api#get_basic_info_about_specefic_city"

    get "say_warning" => "v1::api#say_warning"
    get "say_thanks" => "v1::api#say_thanks"

    get "get_watchdog_list" => "v1::api#get_watchdog_list"
    get "broadcasts" => "v1::api#broadcasts"
  end
  
  root to: "home_page#index"

  get "/review", to: "reviews#new", as: "review"
  post "/post", to: "reviews#create", as: "post_review"
  get "/search", to: "home_page#search"
  
  
  match "howitworks", to: "home_page#tour", as: "howitworks"
  match "terms", to: "home_page#terms", as: "terms"
  match "support", to: "home_page#support", as: "support"

  get "cities", to: "city#index", as: "cities"
  get "cities/:url_type", to: "city#show", as: "city"

  get '/top', to: "users#top", as: "user_top"
  get '/:phone_number', to: "users#show", as: :user
  get '/:phone_number/transports', to: "users#transports", as: "user_transports"
  

end

app/views/layouts/_footer.html.erb
<!-- <div class="container">
 <div class="footer">
  <div class="container footer-element">
    <%= link_to "#{ t 'contacts'}", home_page_contacts_path %> |
     <%= link_to "#{ t 'terms'}", home_page_terms_path %> |
     <%= link_to "#{t 'reviews'}", review_path %> <br />
    <%= link_to "WIMB", root_path %> © <%= Time.now.year %>
  </div>
 </div>
</div> -->


<footer class="container footer-box">   
  <hr class="shadow-line" />         
  <nav class="links">             
      <a href="#">About</a>
      <a href="#">Tour</a>
      <a href="#">Blog</a>
      <a href="#">Terms of Use</a>
      <a href="#">Support</a>                   
  </nav>  
  <nav class="links">
<!--       <a href="#"><img src="<%= asset_path 'twitter-icon.png' %>" alt="twitter"></a>
      <a href="#"><img src="<%= asset_path 'facebook-icon.png' %>" alt="fb"></a>   
      <a href="#"><img src="<%= asset_path 'googleplus-icon.png' %>" alt="gplus"></a>   -->    
      <%= Time.now.year %>
  </nav>                        
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= yield(:title) %></title>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,600" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
					window.currentGuest = {
						location: "<%= @current_city %>"
					};

					console.log(window.currentGuest);
  </script>
  <%= yield(:google_chart_framework) %>
</head>
<body>
  <% if yield(:header) != nil %>
    <%= yield(:header) %> 
  <% else %>
  <section class="container">
    <nav class="navbar">
        <div class="navbar-inner">
            <div class="container">
                <a href="/" class="brand">WIMB.in</a>
                <ul class="nav">
                    <li><%= link_to "#{t 'home'}", root_path %></li>
                    <li> <%= link_to "#{t 'howitworks'}", howitworks_path %> </li>
                    <li> <%= link_to "#{t 'blog'}", home_page_blog_path %> </li>
                </ul>
            </div>
        </div>
    </nav>
  </section>
  <% end %>

  
  <%= yield(:content) %>
  

  <footer class="container footer-box">   
      <hr class="shadow-line" />         
      <nav class="links">
          <%= link_to "#{t 'howitworks'}", howitworks_path %>    
          <%= link_to "#{t 'blog'}", "http://blog.wimb.in", target: "_blank" %> 
          <%= link_to "#{t 'terms'}", terms_path %> 
          <%= link_to "#{t 'support'}", support_path %>                              
      </nav>  
      
   <!--        <a href="#"><img src="<%= asset_path 'twitter-icon.png' %>" alt="twitter"></a>
          <a href="www.facebook.com/wimbin"><img src="<%= asset_path 'facebook-icon.png' %>" alt="fb"></a>   
          <a href="#"><img src="<%= asset_path 'googleplus-icon.png' %>" alt="gplus"></a>     -->  
          <%= "#{Time.now.year} WIMB - All rights reserved." %>
                              
  </footer>

  <%= javascript_include_tag "application" %>
</body>
</html>